In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('pre-data.csv')
dataset.head()

Id Country   Age  Insurance
0   1   China  30.0    10500.0
1   2   India  31.0        NaN
2   3  Poland  30.0    15000.0
3   4   China   NaN    16000.0
4   5   India  30.0    17000.0

# Missing Data Handling – Pre Processing

In [4]:
X = dataset.iloc[:,2:4].values #Takes all rows of all columns 

In [5]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy="mean")
X = imp.fit_transform(X)

In [6]:
X

array([[   30.        , 10500.        ],
       [   31.        , 12255.55555556],
       [   30.        , 15000.        ],
       [   30.26829268, 16000.        ],
       [   30.        , 17000.        ],
       [   34.        , 19000.        ],
       [   30.        , 20000.        ],
       [   30.        , 19000.        ],
       [   30.        , 14000.        ],
       [   38.        , 10000.        ],
       [   28.        , 12255.55555556],
       [   30.        , 10000.        ],
       [   30.        , 16000.        ],
       [   30.        , 10000.        ],
       [   30.        , 18000.        ],
       [   30.        , 10000.        ],
       [   30.26829268, 10000.        ],
       [   30.        , 16000.        ],
       [   30.        , 10000.        ],
       [   30.        , 13000.        ],
       [   30.        , 10000.        ],
       [   30.        , 13000.        ],
       [   30.        , 10000.        ],
       [   30.        , 14000.        ],
       [   30.26

# Categorical Data Handling – Pre Processing

In [17]:
# Using one hot encoding we will create a dummy variable for each of the category in the column.

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [8]:
lab_enc = LabelEncoder()
X = dataset.iloc[:,1:2].values

In [9]:
X[:,0]= lab_enc.fit_transform(X[:,0])

In [10]:
oh_enc = OneHotEncoder(categorical_features = [0])

In [11]:
X = oh_enc.fit_transform(X).toarray()
X

d:\pdocs\9_upwork\steven_video\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
d:\pdocs\9_upwork\steven_video\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [43]:
#The the above 3 columns are the dummy features representing China,India and Poland respectively.
#The 1’s in these columns indicate that the person belongs to that country.

# Splitting into Train and Test set

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = dataset.iloc[:,:-1].values #Takes all rows of all columns except the last column
Y = dataset.iloc[:,-1].values # Takes all rows of the last column

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

In [17]:
len(X_train),len(Y_train)

(34, 34)

In [18]:
len(X_test),len(Y_test)

(15, 15)

# Feature Scaling – Pre Processing

In [53]:
from sklearn.preprocessing import StandardScaler

In [56]:
X_sc = dataset.iloc[:,2:4].values
X_sc

array([[   30., 10500.],
       [   31.,    nan],
       [   30., 15000.],
       [   nan, 16000.],
       [   30., 17000.],
       [   34., 19000.],
       [   30., 20000.],
       [   30., 19000.],
       [   30., 14000.],
       [   38., 10000.],
       [   28.,    nan],
       [   30., 10000.],
       [   30., 16000.],
       [   30., 10000.],
       [   30., 18000.],
       [   30., 10000.],
       [   nan, 10000.],
       [   30., 16000.],
       [   30., 10000.],
       [   30., 13000.],
       [   30., 10000.],
       [   30., 13000.],
       [   30., 10000.],
       [   30., 14000.],
       [   nan, 10000.],
       [   30., 10000.],
       [   30., 12000.],
       [   30., 11000.],
       [   30.,    nan],
       [   30., 10000.],
       [   30., 15000.],
       [   30., 10000.],
       [   30., 10000.],
       [   30., 15000.],
       [   nan, 10000.],
       [   30., 10000.],
       [   nan, 10000.],
       [   30., 10000.],
       [   30., 10000.],
       [   30., 10000.],


In [57]:
sc_ex = StandardScaler()
X_scaled = sc_ex.fit_transform(X_sc)
X_scaled

array([[-0.18965517, -0.57997372],
       [ 0.51724138,         nan],
       [-0.18965517,  0.90666778],
       [        nan,  1.23703255],
       [-0.18965517,  1.56739733],
       [ 2.63793103,  2.22812689],
       [-0.18965517,  2.55849166],
       [-0.18965517,  2.22812689],
       [-0.18965517,  0.576303  ],
       [ 5.46551724, -0.74515611],
       [-1.60344828,         nan],
       [-0.18965517, -0.74515611],
       [-0.18965517,  1.23703255],
       [-0.18965517, -0.74515611],
       [-0.18965517,  1.89776211],
       [-0.18965517, -0.74515611],
       [        nan, -0.74515611],
       [-0.18965517,  1.23703255],
       [-0.18965517, -0.74515611],
       [-0.18965517,  0.24593822],
       [-0.18965517, -0.74515611],
       [-0.18965517,  0.24593822],
       [-0.18965517, -0.74515611],
       [-0.18965517,  0.576303  ],
       [        nan, -0.74515611],
       [-0.18965517, -0.74515611],
       [-0.18965517, -0.08442655],
       [-0.18965517, -0.41479133],
       [-0.18965517,